// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// IRedisController is an autogenerated mock type for the IRedisController type
type IRedisController struct {
	mock.Mock
}

// Del provides a mock function with given fields: c
func (_m *IRedisController) Del(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: c
func (_m *IRedisController) Get(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: c
func (_m *IRedisController) Set(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIRedisController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRedisController creates a new instance of IRedisController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRedisController(t mockConstructorTestingTNewIRedisController) *IRedisController {
	mock := &IRedisController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
