// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRouter is an autogenerated mock type for the IRouter type
type IRouter struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *IRouter) New() {
	_m.Called()
}

type mockConstructorTestingTNewIRouter interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRouter creates a new instance of IRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRouter(t mockConstructorTestingTNewIRouter) *IRouter {
	mock := &IRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
